sonar.projectKey=kadashee_frontend-project-11
sonar.organization=kadashee
sonar.host.url=https://sonarcloud.io

# Path to source directories
sonar.sources=src

# Exclude files from analysis
sonar.exclusions=node_modules/**,dist/**,**/*.test.js
